- denops/skkeleton/deps.ts
- denops/skkeleton/deps/denops_test.ts
- denops/skkeleton/function/disable.ts
- denops/skkeleton/function/input_test.ts
- denops/skkeleton/main.ts
* setlocal ではなく op を使う
* 警告の修正
> Fix TypeScript code

- denops/ddc-sources/skkeleton.ts
補完したときアノテーションが挿入されてしまったので修正しました。
> Fix annotation

- autoload/skkeleton.vim
- denops/skkeleton/main.ts
補完ウィンドウで、Tabが動作する一方で、Shift-Tabが動かなかったため修正しました。
> fix Shift-Tab doensn't work in completion

- denops/skkeleton/main.ts
because skkeleton#toggle is not worked
> fix: disable in replace mode

- denops/skkeleton/function/common.ts
- denops/skkeleton/function/common_test.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/function/henkan_test.ts
- denops/skkeleton/function/input_test.ts
- denops/skkeleton/function/mode.ts
- denops/skkeleton/function/testutil.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/main.ts
~~今までは補完候補を単純に辞書から集めて出力していただけでしたが、このパッチを適用すると最近使った候補を記録するようになります。
デフォルトでは、記録はするがVimを終了すると消える状態になります。`completionRankFile`を設定すると保存されるようになります。
また、これに付随して辞書周りのリファクタリングを行っています~~
一旦リファクタリングのみ取り込みます
> Improve dict

- denops/skkeleton/function/jisyo.ts
- denops/skkeleton/function/mode.ts
> fix: open cmdwin at cancel register dictionary when 'cedit' is `<C-c>`

- denops/skkeleton/function.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/keymap.ts
- doc/skkeleton-functions.jax
> feat: key bind of purge registered candidate

- denops/skkeleton/jisyo.ts
```typescript
import { SKKDictionary } from "./jisyo.ts";
const dic = new SKKDictionary();
let t1 = performance.now();
await dic.load("c:/users/mattn/SKK-JISYO.L", "utf-8");
let t2 = performance.now();
console.log(`load ${t2 - t1} ms`);
```
before
>load 893.2183 ms
after
>load 431.1175999999996 ms
> Optimization for load dictionary

- denops/skkeleton/main.ts
skkleton eggLikeNewLine が pum.vim に対応してなかったので修正
> feat: add pum.vim support for eggLikeNewLine

- denops/skkeleton/main.ts
> test: Fix type

- denops/skkeleton/jisyo.ts
> fix typing of getCandidate

- denops/skkeleton/function/jisyo.ts
> Use silent! for unmap

- denops/skkeleton/context.ts
- denops/skkeleton/function/disable.ts
- denops/skkeleton/main.ts
> Save textwidth

- denops/skkeleton/config.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/main.ts
- denops/skkeleton/testdata/globalJisyo2
- doc/skkeleton.jax
複数のグローバル辞書を使えるようにし、それに伴い設定項目を追加しました
> feat: multi dictionary config

- denops/skkeleton/jisyo.ts
- denops/skkeleton/main.ts
Fix #24 
機能としては完成しています。実装としてこれでよいかチェックをお願いします。
> Improve completion behavior

- denops/skkeleton/config.ts
- denops/skkeleton/function/common.ts
- denops/skkeleton/function/mode.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/kana_test.ts
- denops/skkeleton/main.ts
- doc/skkeleton.jax
> feat: kanaTable config

- denops/skkeleton/jisyo.ts
> Implement the completion for skkserver

- denops/@ddc-sources/skkeleton.ts
- denops/skkeleton/main.ts
> fix: handling `CompleteDone` truely

- autoload/skkeleton.vim
> fix: broken key notation normalizer

- denops/skkeleton/config_test.ts
- denops/skkeleton/function/common.ts
- denops/skkeleton/function/common_test.ts
- denops/skkeleton/function/disable_test.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/function/henkan_test.ts
- denops/skkeleton/function/input_test.ts
- denops/skkeleton/function/jisyo.ts
- denops/skkeleton/function/jisyo_test.ts
- denops/skkeleton/function/mode.ts
- denops/skkeleton/function/mode_test.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/kana_test.ts
- denops/skkeleton/keymap_test.ts
- denops/skkeleton/main.ts
- denops/skkeleton/store.ts
- denops/skkeleton/testutil.ts
> fix: import entrypoint from other scripts is breaking behavior

- denops/skkeleton/main.ts
> Fix marker check

- autoload/skkeleton.vim
- denops/@ddc-sources/skkeleton.ts
- denops/skkeleton/keymap_test.ts
- denops/skkeleton/main.ts
Fix #103
補完状態を処理するのをやめてバッファとpreEditの相違だけ見るようにしてみた
> fix: improve completion handling

- autoload/skkeleton.vim
- denops/skkeleton/deps.ts
- denops/skkeleton/function/jisyo.ts
- denops/skkeleton/main.ts
Fix #114
こちらの問題について、cmdlineでステートの初期化を行っていないことが根本原因なので正しく行うように変更します
> fix: will initialize state at cmdline leave

- denops/skkeleton/main.ts
> Fix initialize when handleCompleteKey

- denops/skkeleton/function.ts
- denops/skkeleton/function/mode.ts
- denops/skkeleton/main.ts
> Add: zenkaku to hirakana

- autoload/skkeleton.vim
`skkeleton#initialize()` が遅いマシンでエラーになるので修正。
> Add skkeleton#notify_async()

- autoload/skkeleton.vim
> Improve skkeleton#handle()

- denops/skkeleton/function/henkan.ts
- denops/skkeleton/jisyo.ts
> fix: doesn't work `immediatelyJisyoRW` when completion

- doc/skkeleton.jax
Fix #141 
環境依存であるしユーザー設定でなんとかできるので FAQ に追加。
> Add FAQ for cursor

- denops/@ddc-sources/skkeleton.ts
Preview comments of jisyo entries
> feat(ddc): Add previewer

- denops/skkeleton/keymap_test.ts
- denops/skkeleton/main.ts
`handleKey`の key に複数の key を送れるようにしてみました。
> feat: make it possible to send multiple keys with handleKey

- README.md
- denops/skkeleton/deps/std/streams.ts
- denops/skkeleton/jisyo.ts
> Remove deprecated iterateReader

- denops/skkeleton/deps/std/async.ts
- denops/skkeleton/jisyo/google_japanese_input.ts
Google API が遅いことがあるのでタイムアウトを設定しました。
> Add timeout for Google API

- denops/skkeleton/jisyo/skk_server.ts
> Fix iterLine() errors

- denops/skkeleton/function/henkan.ts
> fix: can't cancel select candidates

- denops/skkeleton/jisyo/skk_server.ts
> Fix skkServer hang up

- denops/skkeleton/dictionary.ts
- denops/skkeleton/dictionary_test.ts
- denops/skkeleton/sources/deno_kv.ts
- denops/skkeleton/sources/google_japanese_input.ts
- denops/skkeleton/sources/skk_dictionary.ts
- denops/skkeleton/sources/skk_server.ts
- denops/skkeleton/sources/user_dictionary.ts
- denops/skkeleton/store.ts
> Add Source type

- denops/skkeleton/dictionary.ts
- denops/skkeleton/dictionary_test.ts
- denops/skkeleton/function/mode_test.ts
- denops/skkeleton/main.ts
- denops/skkeleton/sources/deno_kv.ts
- denops/skkeleton/sources/google_japanese_input.ts
- denops/skkeleton/sources/skk_dictionary.ts
- denops/skkeleton/sources/skk_server.ts
- denops/skkeleton/sources/user_dictionary.ts
- denops/skkeleton/store.ts
- denops/skkeleton/testutil.ts
- denops/skkeleton/util.ts
source をモジュールとして間接的にロードするようにしました。これによりユーザーが自由に source を追加することも可能です。
> Load sources as module

- denops/skkeleton/sources/deno_kv.ts
> Add Deno.KV check

- autoload/skkeleton/internal/map.vim
> Fix mapset() arguments

- denops/skkeleton/function/henkan.ts
> Fix candidates msg

- denops/skkeleton/deps/ddc/filter.ts
- denops/skkeleton/deps/ddc/source.ts
- denops/skkeleton/deps/ddc/types.ts
- denops/skkeleton/deps/denops_test.ts
> Don't use -pre modules

- denops/skkeleton/deps/unknownutil.ts
> Use JSR for unknownutil

- denops/skkeleton/sources/skk_server.ts
- denops/skkeleton/util.ts
Fix #206 
Reference: https://www.npmjs.com/package/encoding-japanese
> Fix encoding error

- denops/skkeleton/config.ts
- denops/skkeleton/function/input.ts
- denops/skkeleton/function/input_test.ts
- denops/skkeleton/types.ts
- doc/skkeleton.jax
> feat: add downcaseMap option for fix can't use symbol as kana with shift

- doc/skkeleton.jax
I have added the language annotation for help.
> Add language annotation

- autoload/skkeleton/popup.vim
- denops/skkeleton/config.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/types.ts
- doc/skkeleton.jax
実装の簡略化及び今後の機能追加のために `usePopup` オプションを廃止しpopupに一本化する
> feat!: abolish `usePopup` option

- doc/skkeleton.jax
ドキュメントフォーマットが一部おかしかったので修正入れました
> Fix the documentation format

- denops/skkeleton/function/disable_test.ts
- denops/skkeleton/function/mode_test.ts
- denops/skkeleton/main.ts
Fix #219
補完判定のタイミングを変更してついでにリファクタリングした
> fix: allow disable when just after completion
