vim-skk/skkeleton

- denops/skkeleton/config.ts
- denops/skkeleton/function/disable.ts
- doc/skkeleton.jax
`keepState` がtrueのとき、skkが有効なInsertモードから抜けたら次に入る時にskkを自動で有効にするようになります
> Add keepState config

- denops/skkeleton/function/input.ts
`register_kanatable` で大文字アルファベットを使ったマッピングを可能にします。
AquaSKK では「Q」を押すことで「見出し語入力モード」（≒ `henkanPoint`）に入れます。
https://ja.osdn.net/projects/aquaskk/wiki/keymap.confの文法
しかし現行の `register_kanatable` に以下のように指定しても無視されてしまいます。そのままだと大文字アルファベットは小文字に変換されて `henkanPoint` に渡されるためです。
```vim
call skkeleton#register_kanatable('rom', {'Q': 'henkanPoint'})
```
そこで、`<s-q>` という記述で大文字の「Q」を渡せるようにしてみました。これで AquaSKK と同じ動作が実現できます。
```vim
" Q → henkanPoint
call skkeleton#register_kanatable('rom', {'<s-q>': 'henkanPoint'})
```
複数の文字列を組み合わせても動きます（実用的かどうかはさておき）。
```vim
" HEllo → ほげほげ
call skkeleton#register_kanatable('rom': {'<s-h><s-e>llo': ['ほげほげ', '']})
```
一応やりたいことは実現できたのですが、`register_kanatable` の仕様としてこれで良いのか、などご相談したいです。
> Enable to register upper cases to kana table

- denops/skkeleton/main.ts
特定の操作をすると`vimStatus`が定義されていない状態で進行してしまうことがあるようなのですが、そのハンドリングがうまくできておらずエラーが発生することがあったため修正しました。
現在のコードだと、`vimStatus`がundefinedでも動作してしまうようです。
```typescript
console.log(true || false && true && false) // true
```
修正のやり方はマージする際に適宜変えてください。
一応エラーの再現手順も記載しておきます。
どうしてこの操作でエラーになるのかはよく分かりません…
```
OS: Windows 10
neovim-version: NVIM v0.6.0-dev+356-gbec7f47ce
skkeleton-version: 3fee9c8
```
```vim
" minivimrc
set rtp+=~\.cache\dein\repos\github.com\vim-denops\denops.vim
set rtp+=~\.cache\dein\repos\github.com\kuuote\denops-skkeleton.vim
imap <C-j> <Plug>(skkeleton-enable)
cmap <C-j> <Plug>(skkeleton-enable)
```
1.  `nvim -u minivimrc`
2.  i
3.  Ctrl-j
4.  ESC
5.  :
6.  Ctrl-j
7. エラー
```
Error invoking 'invoke' on channel 4:
Error: Failed to call 'enable' with []: EnsureError: The value must be string …
```
> fix EnsureString error

- denops/skkeleton/main.ts
Fix #43 
Fix https://github.com/delphinus/skkeleton_indicator.nvim/issues/3
`handleKey()` を呼ぶ前後で mode が変わっていたら `''` ではなく <kbd>Space</kbd> + <kbd>Backspace</kbd> を返すことで描画を更新するようにしてみました。一応意図した通りに動いてますがもっと綺麗にできないか……
> Add a stopgap measure to inform mode change

- doc/skkeleton.jax
augroupの部分が設定できなくて、辞書が読み込めなかったりしていました。
確認よろしくお願いします。
> fix typo in document.

- denops/@ddc-filters/skkeleton.ts
- denops/@ddc-sources/skkeleton.ts
- denops/skkeleton/config.ts
- denops/skkeleton/deps/ddc/filter.ts
- denops/skkeleton/deps/ddc/source.ts
- denops/skkeleton/deps/ddc/types.ts
- denops/skkeleton/deps/iterator_helpers.ts
- denops/skkeleton/deps/std/collections.ts
- denops/skkeleton/deps/std/io.ts
- denops/skkeleton/deps/std/path.ts
- denops/skkeleton/deps/std/testing.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/main.ts
- denops/skkeleton/types.ts
- doc/skkeleton.jax
#27
候補が増えるほど補完候補の順番が不便な並びになる問題への対処として、 `completionRankFile` オプションを追加し、最近使った候補の順番を記録できるようにします
> Feat completion rank

- denops/skkeleton/function/common.ts
- denops/skkeleton/function/jisyo.ts
- denops/skkeleton/function/mode_test.ts
- denops/skkeleton/state.ts
カタカナモードで送り仮名ありの変換をすると送り仮名がひらがなになっていたので直しました
> fix: can't convert okuri string properly when mode changed

- denops/skkeleton/main.ts
`<Plug>(skkeleton-toggle)`の中でskkeletonを有効にするか無効にするか判断するとき、
`g:skkeleton#mode`の値も参照することで、有効になっていないのに無効にしようとする場合に対処できると思います。
(例: `<Plug>(skkeleton-toggle)`の前に`<C-^>`してしまったとき)
> fix: skkeleton-toggle calls skkeleton-disable before skkeleton-enable

- denops/skkeleton/deps/std/io.ts
- denops/skkeleton/deps/std/streams.ts
- denops/skkeleton/jisyo.ts
Close #71
`iter()` was moved to [`streams/conversion.ts`](https://deno.land/std@0.127.0/streams/conversion.ts) as `iterateReader`.
> fix: Replace deprecated function

- denops/skkeleton/deps/roman.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/testdata/numJisyo
http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=%CD%D7%CB%BE#p12
`#8'
タイプ 8。ローマ数字変換。`1789' を 'MDCCLXXXIX' に変換します。
> Add roman number conversion

- autoload/skkeleton.vim
`luaeval('pcall(require, "cmp")')` はプラグイン未インストールのときでも true を返すことがあります。ちゃんと型をチェックするように修正しました。
Note: これが発覚したのは、テスト用の `cmp.lua` がカレントディレクトリにあったためです。
> Fix lua check

- autoload/skkeleton.vim
- plugin/skkeleton.vim
exprマッピング(のtextlock)が `denops#plugin#wait()` を失敗させることがあるのでやめる
> fix: expr(textlock) breaks `denops#plugin#wait()` at some case

- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/testdata/numIncludingJisyo
If a word in a dictionary has any number, let's say "cat2"(🐈) or "100"(💯), it doesn't appear in candidates, and then the word cannot be converted, no matter what word you type.
So I fixed it.
> fix: add words including numbers to candidates

- denops/skkeleton/jisyo.ts
- doc/skkeleton.jax
「▽い」のような1文字の候補を入力した際に完全一致する変換候補を補完するようにします
> feat: can get exact completion item at short input

- denops/skkeleton/deps.ts
gatherはどこでも使われていないようなので、collectに置き換えるのではなく完全に削除する
> Remove import `gather` deleted in denops v5

- autoload/skkeleton.vim
- denops/skkeleton/keymap.ts
- doc/skkeleton.jax
`<C-space>`, `<S-space>` のマッピングを削除します。副作用が大きいためです。
> Remove some default mappings

- autoload/skkeleton.vim
- denops/skkeleton/function/disable_test.ts
- denops/skkeleton/function/input_test.ts
- denops/skkeleton/main.ts
- doc/skkeleton.jax
#113 を解決します。
変数 `g:skkeleton#state` 及び、それにアクセスするためのイベント `skkeleton-handled` を追加します。
`g:skkeleton#state` は現時点で以下の要素を持ちます。
```
phase: 入力の段階
"input"            直接入力
"input:okurinasi"  送りなし入力
"input:okuriari"   送りあり入力
"henkan"           変換
```
> feat: add state view via g:skkeleton#state

- denops/skkeleton/config.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/kana.ts
- denops/skkeleton/main.ts
- denops/skkeleton/types.ts
- denops/skkeleton/util.ts
- doc/skkeleton.jax
SKKの「拡張設定ファイル」をかなテーブルとして読み込めるようにします。 (configの`globalKanaTableFiles`)
<br />
AZIKの拡張設定を読みこんだ様子です。
azik_us.ruleを読みこむことで、`xa→しゃ` `jk→じん` などのローマ字入力が追加されています
(動画にて読みこんでいる.ruleは私のdotfilesにあるものです)
https://github.com/AsPulse/dotfiles-mac/blob/ccf0703b7cae0965b7c43bb49d0246ccaff29236/AquaSKK/azik_us.rule#L100-L111
https://github.com/vim-skk/skkeleton/assets/84216737/0014fe2d-3b5c-40c4-bb32-98d68ce67a55
<br />
今まで かなテーブルを編集したり、ファイルを読みこんだりするのが一箇所だったので  
必然的に共通化みたいなことを多くすることになりました……。
- **`readFileWithEncoding` 関数を追加しました。**
エンコーディング指定してファイルを読みこむ処理は`globalDictionaries`のみだったのですが、今回追加する`globalKanaTableFiles`もこの処理を行うので共通化しました。
- **`homeExpand`関数が`homePath: string`の代わりに`denops: Denops`を取るようになり、`utils.ts`へ移動しました**
同じく`homeExpand`を使っていたのはinit内のみだったのですが、config内でも使うようになったため共通化しました。
- …
> かなテーブル(.rules)を読み込めるようにする

- denops/skkeleton/config.ts
- denops/skkeleton/config_test.ts
- denops/skkeleton/function/input.ts
- denops/skkeleton/okuri.ts
- denops/skkeleton/types.ts
- doc/skkeleton.jax
送りあり変換で「ひるがえっ」等と打った段階でタ行扱いして「翻っ」のように変換する機能を追加します。
これにより #138 が解決する予定です。
> feat: can immediately convert at っ when okuriari mode

- autoload/skkeleton.vim
- denops/skkeleton/keymap_test.ts
`skkeleton#register_keymap()`に大文字を一文字だけ(例えば`A`)登録すると、`keyMap.map`のキーの値は`<s-a>`になります。
一方、`keymap.ts`の`handleKey()`では、`notationToKey[key] ?? key`の結果`registerKeyMap()`に`A`を渡しており、マップが参照できなくなっていました。
https://github.com/vim-skk/skkeleton/blob/fbdfe6e48de08d9ca1116683b796de95bd6ef83c/denops/skkeleton/keymap.ts#L50-L62
> Fix a bug, where you cannot register a single capital letter with skkeleton#register_keymap().

- .github/workflows/test.yml
macOS の Runner は頻繁に失敗するので無意味だとおもいます
> Remove macos runner

- denops/skkeleton/config.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/main.ts
- denops/skkeleton/types.ts
- doc/skkeleton.jax
Google 日本語入力 API に対応させてみました
https://www.google.co.jp/ime/cgiapi.html
> Add GoogleJapaneseInput support

- denops/@ddc-sources/skkeleton.ts
- denops/skkeleton/config_test.ts
- denops/skkeleton/function/common.ts
- denops/skkeleton/function/common_test.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/function/henkan_test.ts
- denops/skkeleton/function/mode.ts
- denops/skkeleton/function/mode_test.ts
- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo_test.ts
- denops/skkeleton/keymap_test.ts
- denops/skkeleton/main.ts
`getCandidate()`, `getCandidates()` の役割の違いが一目見て分からないのでリネームしました。
> Rename getCandidate() and getCandidates()

- denops/skkeleton/jisyo.ts
Google API による変換は送りなしのときにのみ有効とします。
> GoogleJapaneseInput should not work for okuriari

- autoload/skkeleton.vim
Vimでwaitする際に入力が吸われて不便なので改善してみる
> fix: replace `denops#plugin#wait()` because absorbs input in Vim

- denops/skkeleton/jisyo.ts
- denops/skkeleton/jisyo/skk_dictionary.ts
- denops/skkeleton/jisyo_test.ts
> Improve skk_dictionary

- denops/skkeleton/config.ts
- denops/skkeleton/dictionary.ts
- denops/skkeleton/main.ts
databasePathがexpandされない問題の修正
同時に、setConfigの時点でパスにはhomeExpandを実行するようにします。
> expand databasePath

- denops/skkeleton/dictionary.ts
- denops/skkeleton/dictionary_test.ts
- denops/skkeleton/main.ts
> Fix loadDictionary() initializer

- denops/skkeleton/function/disable.ts
`keepState` を有効にしているとエラーになるので修正。
> Fix "enable" method error

- denops/skkeleton/sources/deno_kv.ts
```
% deno --version
deno 1.40.4 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3
```
Deno 最新版で補完を使うとエラーが出ていたので修正。
```
[ddc] source: skkeleton "gather()" failed
[ddc] unknown error object
[denops] TypeError: start key is not in the keyspace defined by prefix
[denops]     at KvListIterator.<anonymous> (ext:deno_kv/01_db.ts:141:36)
[denops]     at KvListIterator.next (ext:deno_kv/01_db.ts:579:42)
[denops]     at Dictionary.getCompletionResult (file:///home/shougo/work/skkeleton/denops/skkeleton/sources/deno_kv.ts:138:15)
[denops]     at NumberConvertWrapper.getCompletionResult (file:///home/shougo/work/skkeleton/denops/skkeleton/dictionary.ts:163:42)
[denops]     at Library.getCompletionResult (file:///home/shougo/work/skkeleton/denops/skkeleton/dictionary.ts:248:21) …
```
> Fix Deno KV errors in the latest deno

- denops/skkeleton/sources/deno_kv.ts
#189 に関連
Deno 1.40.3 で prefix と start の併用は禁止されたが、これを単純に削除するだけでは完全一致の候補が取れなくなるので、`kv.get()` を使う必要がある。
> Use `kv.get()` to get candidates from exactly matched prefix

- doc/skkeleton.jax
ドキュメントの文章をより誤解のない形に書き換えました。
型が配列であることから、複数の辞書を指定できることは自明であるためこのような表記にしました
もとのglobalJisyoの記述は下記の通りであるため、同様の形式としました
```
globalJisyo                                     *skkeleton-config-globalJisyo*
(デフォルト "/usr/share/skk/SKK-JISYO.L")
グローバル辞書のパス
圧縮された辞書をそのまま使う機能はないため
辞書が圧縮されている場合は展開する必要があります。
互換性のために残しています。globalDictionariesが指定されていた場合は
無視されます。
```
> Fix skkeleton.jax

- denops/skkeleton/candidate.ts
- denops/skkeleton/function.ts
- denops/skkeleton/function/common.ts
- denops/skkeleton/function/henkan.ts
- denops/skkeleton/function/input.ts
- denops/skkeleton/keymap.ts
- denops/skkeleton/state.ts
- doc/skkeleton-functions.jax
- implement prefix/suffix conversions documented in https://ddskk.readthedocs.io/ja/latest/06_apps.html#id35 .
- adds default mapping `>` to enable the feature
> Feat prefix/suffix conversions

- denops/skkeleton/util.ts
Close #204 
`npm:encoding-japanese@2.2.0` を `import * as` で読み込んでいるのが原因のようだったので修正しました。
> encoding-japanese の import を修正

- denops/@ddc-filters/skkeleton.ts
- denops/@ddc-sources/skkeleton.ts
> Fix warnings: override is needed

- autoload/skkeleton/popup.vim
`winborder` オプションにより border がセットされると表示が崩れるので明示的に指定する必要があります。
> Set border explictly

- denops/@ddc-sources/skkeleton/okurisplits.ts
- denops/@ddc-sources/skkeleton/okurisplits_test.ts
- denops/@ddc-sources/skkeleton_okuri.ts
- denops/skkeleton/dictionary.ts
- denops/skkeleton/main.ts
- doc/skkeleton.jax
例えば「あたり」の場合、「あた+り」=>「辺り」や「あ*たり」=>「当たり」などの候補を出力するような補完ソースを追加します
> 送りあり変換の補完ソースを追加

- autoload/skkeleton.vim
- denops/skkeleton/kana.ts
- denops/skkeleton/main.ts
- doc/skkeleton.jax
#216 
`skkeleton#register_kanatable_file()` を実装してみました。こんな仕様だとどうでしょうか。
`globalKanaTableFiles` は削除してよいと思っていますが、それはやっていません
> Add skkeleton#register_kanatable_file()

- denops/skkeleton/main.ts
[i_CTRL_O](https://vim-jp.org/vimdoc-ja/insert.html#i_CTRL-O) で挿入モードを一時的に抜けた際などに解除されてしまう問題への対処
> fix: unwanted disable when `i_CTRL-O`

- denops/skkeleton/function/henkan.ts
- denops/skkeleton/function/henkan_test.ts
- doc/skkeleton-functions.jax
#183 に対応するために `henkanFirst` 内で直接入力の代わりに `kanaInput` を呼び出すように変更
> feat: fallback to kanaInput at henkanFirst 
